### ISSUE TITLE
Error 404 and 500 when trying to use shiftml

### ISSUE THREAD

**Issue by enricoravera** [materialscloud-org/issues#25] opened 2021-06-14 20:31 UTC
Dear Developers, I have been trying to perform shiftml calculations over the past week and the web interface appears unresponsive. Chrome's page analysis tool gives the following messages on opening:

b3241a6b.vendor1.js:1 You are using the ngTouch module. 
AngularJS Material already has mobile click, tap, and swipe support... 
ngTouch is not supported with AngularJS Material!
(anonymous) @ b3241a6b.vendor1.js:1
b3241a6b.vendor1.js:1 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ b3241a6b.vendor1.js:1
bootstrap.min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
visualizer_base.min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
visualizer_input.min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
iframeResizer.contentWindow.min.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
logo_SNSF.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
MARVEL_logo.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
EC-H2020.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
VM136:8 [iFrameSizer][Host page: contentiframe] No response from iFrame. Check iFrameResizer.contentWindow.js has been loaded in iFrame
k @ VM136:8
bootstrap.min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
visualizer_base.min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
visualizer_input.min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
DevTools failed to load source map: Could not parse content for https://www.materialscloud.org/work/tools/iframeResizer.map: Unexpected token < in JSON at position 0

Clickin on "calculate shifts" button yields the following messages:

jquery-3.1.0.min.js:4 POST https://tools.materialscloud.org/shiftml/compute/process_structure/ 500 (INTERNAL SERVER ERROR)
send @ jquery-3.1.0.min.js:4
ajax @ jquery-3.1.0.min.js:4
(anonymous) @ (index):452
dispatch @ jquery-3.1.0.min.js:3
q.handle @ jquery-3.1.0.min.js:3
(index):472 Uncaught TypeError: Cannot read property 'message' of undefined
    at Object.error ((index):472)
    at i (jquery-3.1.0.min.js:2)
    at Object.fireWith [as rejectWith] (jquery-3.1.0.min.js:2)
    at A (jquery-3.1.0.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-3.1.0.min.js:4)
error @ (index):472
i @ jquery-3.1.0.min.js:2
fireWith @ jquery-3.1.0.min.js:2
A @ jquery-3.1.0.min.js:4
(anonymous) @ jquery-3.1.0.min.js:4
load (async)
send @ jquery-3.1.0.min.js:4
ajax @ jquery-3.1.0.min.js:4
(anonymous) @ (index):452
dispatch @ jquery-3.1.0.min.js:3
q.handle @ jquery-3.1.0.min.js:3

Best, 

E.

**Comment by ltalirz** [comment] 2021-06-17 22:51
Hey @enricoravera , thank you for the report.
I think the issue is fixed now, can you please check?

@elsapassaro Are you receiving notifications from this repository?
The shiftml tool was broken (landing page worked but clicking on the example did not).
Looking into the machine it turns out that the redis container had exited 10 days ago

```
ubuntu@tools:~$ docker ps -a | grep shiftml
50ea58848f22        shiftml_celery                                   "bash -c 'cd /home/a…"   12 months ago       Up 21 minutes               80/tcp, 443/tcp                                                                              shiftml_celery_1
73cc03ec8c94        shiftml_website                                  "/sbin/my_init"          12 months ago       Up 6 days                   443/tcp, 0.0.0.0:3246->80/tcp                                                                shiftml_website_1
28be5058544f        tools-barebone-shiftml                           "/sbin/my_init"          12 months ago       Exited (255) 7 months ago   443/tcp, 0.0.0.0:3255->80/tcp                                                                tools-barebone-shiftml-instance
385ec7a163c3        redis:4.0.8-alpine                               "docker-entrypoint.s…"   20 months ago       Exited (0) 10 days ago                                                                                                   shiftml_redis_1
```

After restarting the container the tool started working again.

This is the relevant log from the container - it seems it was shut down on June 5th and never restarted.
```
...
1:M 18 Feb 17:50:14.784 * Ready to accept connections
1:signal-handler (1623045553) Received SIGTERM scheduling shutdown...
1:M 07 Jun 05:59:13.862 # User requested shutdown...
1:M 07 Jun 05:59:13.862 # Redis is now ready to exit, bye bye...
1:C 17 Jun 22:47:13.375 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 17 Jun 22:47:13.375 # Redis version=4.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 17 Jun 22:47:13.375 # Configuration loaded
1:M 17 Jun 22:47:13.379 * Running mode=standalone, port=6679.
1:M 17 Jun 22:47:13.379 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 17 Jun 22:47:13.379 # Server initialized
...
```

**Comment by elsapassaro** [comment] 2021-06-18 09:01
Thanks @ltalirz for looking into this. I'm watching this repository but I don't know why I didn't receive a notification.

On June 7th I shut down the machine due to the Pollux upgrade, and it seems that this container didn't restart automatically.
Mentioning @vgranata as she's in charge of the tools: should we modify the restart policy of the shiftML containers to always  automatically restart them or there is some reason for which this should be avoided?

**Comment by enricoravera** [comment] 2021-06-18 16:08
Thanks, it works fine. 

Cheers, 

E.

**Closed as completed** 2021-11-25 08:50 UTC
