### ISSUE TITLE
Seekpath incorrent interpretation of cell vectors

### ISSUE THREAD

**Issue by bramuser** [materialscloud-org/issues#21] opened 2020-09-15 11:27 UTC
Hi,

I am trying to get high-symmetry points using Seekpath. The input file containing the coordinates is .xyz. The lattice vectors are 
A 3.81 0 0
B 0 3.81 0
C 0 0 3.81
However, if I fill in these coordinates, the parsed input coordinates that show up after the calculation are
A 3.0 0 0
B 0 3.0 0
C 0 0 3.0
So, Seekpath only considers the number before the decimal point. Is there any way to circumvent this problem?

Kind regards,

Bram

**Comment by ltalirz** [comment] 2020-09-15 12:23
Hi @bramuser , that certainly looks like a bug - could you please attach or copy/paste you xyz file here as well?

Pinging @giovannipizzi about this

**Comment by bramuser** [comment] 2020-09-15 12:45
Hi @ltalirz ,
Unfortunately, Github does not allow me to attach the file. However, you can find it on https://www.cp2k.org/exercises:2018_uzh_cmest:pdos The file is called WO3-cubic.xyz

**Comment by ltalirz** [comment] 2020-09-15 13:00
Thanks @bramuser for the update - I can reproduce that with the xyz file

```
4
WO3; a=3.810000
 W    0.000000    0.000000    0.000000
 O    1.905000    0.000000    0.000000
 O    0.000000    1.905000    0.000000
 O    0.000000    0.000000    1.905000
```
and correctly (manually) entered cell vectors one ends up with 

![image](https://user-images.githubusercontent.com/1053245/93213169-ceb4cd80-f763-11ea-9d38-1c931ac715ec.png)

It almost looks like somewhere in https://github.com/materialscloud-org/tools-seekpath the numbers entered into the input fields are converted to integers...

**Comment by ltalirz** [comment] 2020-09-15 14:08
I believe the issue was in tools-barebone https://github.com/materialscloud-org/tools-barebone/issues/19

I've opened a PR and will leave any further fixes to @giovannipizzi

**Comment by bramuser** [comment] 2020-09-15 14:35
Hi @ltalirz , I checked https://github.com/materialscloud-org/tools-barebone/pull/20 and it seems as if you changed something which should solve the issue? However, I just tried it again, and experienced the same issue as before.

**Comment by ltalirz** [comment] 2020-09-15 15:46
Hi @bramuser , sorry - it will take a bit of time for these fixes to propagate to the production server.
@giovannipizzi will ping you once this is the case.

**Comment by ltalirz** [comment] 2020-10-01 08:44
Just mentioning @asle85 who planned to work on this

PR with fix is open in tools-barebone https://github.com/materialscloud-org/tools-barebone/pull/20
Will need to be propagated to tools-seekpath

**Comment by giovannipizzi** [comment] 2020-11-05 21:11
Hi @bramuser thanks for reporting this, and thanks @ltalirz for providing a fix.
I've merged it, created a new release of tools-barebone and of tools-seekpath, and depoyed it.

Now the fix should work in production.

**Closed as completed by giovannipizzi** 2020-11-05 21:11 UTC
